# Generated by Django 4.1.2 on 2022-11-23 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_unitorder_price_alter_unitorder_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.order'),
        ),
    ]
