# Generated by Django 4.1.2 on 2022-11-23 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_alter_order_address_city_alter_order_address_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
