# Generated by Django 4.1.2 on 2022-11-25 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_alter_order_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_street',
            field=models.CharField(max_length=256, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Ordered by'),
        ),
    ]
