# Generated by Django 4.1.2 on 2022-11-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_street',
            field=models.CharField(max_length=256, verbose_name=''),
        ),
    ]
