# Generated by Django 4.1.2 on 2022-11-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_address_street_alter_order_order_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
    ]
