
# Generated by Django 4.1.2 on 2022-11-29 18:02


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_wishlist'),
        ('store', '0013_alter_order_order_by'),
    ]

    operations = [
    ]
