# Generated by Django 4.1.2 on 2022-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_merge_0008_wishlist_0013_alter_order_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.CharField(default='{}', max_length=2048),
        ),
    ]
