# Generated by Django 4.1.2 on 2022-11-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_merge_0008_wishlist_0013_alter_order_order_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitorder',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AlterField(
            model_name='unitorder',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.CharField(default='{}', max_length=2048),
        ),
    ]
