# Generated by Django 4.1.2 on 2022-12-01 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_unitorder_order_id_alter_unitorder_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_city',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'You have to use only letters in this form')], verbose_name='City name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{3}$', 'Postal code must be numbers in form of "00-000"')]),
        ),
    ]
