# Generated by Django 4.1.2 on 2022-11-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_unitorder_order_id_alter_unitorder_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingmethod',
            old_name='shipping_company',
            new_name='shipping_name',
        ),
    ]
