# Generated by Django 4.1.2 on 2022-12-07 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_wishlist_products'),
        ('store', '0017_alter_wishlist_user'),
    ]

    operations = [
    ]
