# Generated by Django 4.1.2 on 2022-12-11 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_wishlistitem_delete_wishlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeCategory',
            new_name='Subcategory',
        ),
        migrations.AlterField(
            model_name='order',
            name='address_postal_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{3}$', "Postal code must be numbers in form of '00-000'")]),
        ),
    ]
