# Generated by Django 4.1.2 on 2022-12-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
